language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
before_script:
    - "ulimit -n 1024"
    - mongo zero --eval 'db.addUser("root", "aa");'
# command to run tests
script: make testall
